### ISSUE TITLE
Cannot build container image on mac

### ISSUE THREAD

**Issue by deepiksdev** [deepiksdev/dialoqbase#6]
Running:
``` 
docker build -t dialoqbasemac .
```
... returns an error:
```
#0 114.0 error /app/node_modules/bufferutil: Command failed.
#0 114.0 Exit code: 1
#0 114.0 Command: node-gyp-build
#0 114.0 Arguments: 
#0 114.0 Directory: /app/node_modules/bufferutil
#0 114.0 Output:
#0 114.0 gyp info it worked if it ends with ok
#0 114.0 gyp info using node-gyp@9.3.1
#0 114.0 gyp info using node@18.16.1 | linux | arm64
#0 114.0 gyp ERR! find Python 
#0 114.0 gyp ERR! find Python Python is not set from command line or npm configuration
#0 114.0 gyp ERR! find Python Python is not set from environment variable PYTHON
#0 114.0 gyp ERR! find Python checking if "python3" can be used
#0 114.0 gyp ERR! find Python - "python3" is not in PATH or produced an error
#0 114.0 gyp ERR! find Python checking if "python" can be used
#0 114.0 gyp ERR! find Python - "python" is not in PATH or produced an error
#0 114.0 gyp ERR! find Python 
#0 114.0 gyp ERR! find Python **********************************************************
#0 114.0 gyp ERR! find Python You need to install the latest version of Python.
#0 114.0 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#0 114.0 gyp ERR! find Python you can try one of the following options:
#0 114.0 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#0 114.0 gyp ERR! find Python   (accepted by both node-gyp and npm)
#0 114.0 gyp ERR! find Python - Set the environment variable PYTHON
#0 114.0 gyp ERR! find Python - Set the npm configuration variable python:
#0 114.0 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#0 114.0 gyp ERR! find Python For more information consult the documentation at:
#0 114.0 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#0 114.0 gyp ERR! find Python **********************************************************
#0 114.0 gyp ERR! find Python 
#0 114.0 gyp ERR! configure error 
#0 114.0 gyp ERR! stack Error: Could not find any Python installation to use
```

**Comment by deepiksdev** [comment]
No longer needed

**Comment by ALLENWAN1** [comment]
@deepiksdev  I successfully create a docker server.  
![image](https://github.com/deepiksdev/dialoqbase/assets/15701831/dc073d3b-9142-44ff-a80f-2cbf77161744)

I think the bug comes from the .env file 
I initialize the DB_SECRET_KEY=123456789

And  I created the docker server by 
![image](https://github.com/deepiksdev/dialoqbase/assets/15701831/2d64946b-e1a8-4675-a1d5-a3efeb49856a)


I hope it helps

**Comment by deepiksdev** [comment]
Thanks a lot @ALLENWAN1 , however this issue is about building the container image using dockerfile.

I have just made another test with a small change, I now get the following error when running `docker build -t dialoqbasemac`:

```
#0 45.09 gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
#0 45.09 gyp http GET https://nodejs.org/download/release/v18.16.1/node-v18.16.1-headers.tar.gz
#0 45.09 gyp http 200 https://nodejs.org/download/release/v18.16.1/node-v18.16.1-headers.tar.gz
#0 45.09 gyp http GET https://nodejs.org/download/release/v18.16.1/SHASUMS256.txt
#0 45.09 gyp http 200 https://nodejs.org/download/release/v18.16.1/SHASUMS256.txt
#0 45.09 gyp info spawn /usr/bin/python3
#0 45.09 gyp info spawn args [
#0 45.09 gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
#0 45.09 gyp info spawn args   'binding.gyp',
#0 45.09 gyp info spawn args   '-f',
#0 45.09 gyp info spawn args   'make',
#0 45.09 gyp info spawn args   '-I',
#0 45.09 gyp info spawn args   '/app/node_modules/bufferutil/build/config.gypi',
#0 45.09 gyp info spawn args   '-I',
#0 45.09 gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
#0 45.09 gyp info spawn args   '-I',
#0 45.09 gyp info spawn args   '/root/.cache/node-gyp/18.16.1/include/node/common.gypi',
#0 45.09 gyp info spawn args   '-Dlibrary=shared_library',
#0 45.09 gyp info spawn args   '-Dvisibility=default',
#0 45.09 gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/18.16.1',
#0 45.09 gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
#0 45.09 gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/18.16.1/<(target_arch)/node.lib',
#0 45.09 gyp info spawn args   '-Dmodule_root_dir=/app/node_modules/bufferutil',
#0 45.09 gyp info spawn args   '-Dnode_engine=v8',
#0 45.09 gyp info spawn args   '--depth=.',
#0 45.09 gyp info spawn args   '--no-parallel',
#0 45.09 gyp info spawn args   '--generator-output',
#0 45.09 gyp info spawn args   'build',
#0 45.09 gyp info spawn args   '-Goutput_dir=.'
#0 45.09 gyp info spawn args ]
#0 45.09 gyp ERR! build error 
#0 45.09 gyp ERR! stack Error: not found: make
#0 45.09 gyp ERR! stack     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:10:17)
#0 45.09 gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:57:18
#0 45.09 gyp ERR! stack     at new Promise (<anonymous>)
#0 45.09 gyp ERR! stack     at step (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:54:21)
#0 45.09 gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:71:22
#0 45.09 gyp ERR! stack     at new Promise (<anonymous>)
#0 45.09 gyp ERR! stack     at subStep (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:69:33)
#0 45.09 gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:80:22
#0 45.09 gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
#0 45.09 gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
#0 45.09 gyp ERR! System Linux 5.15.49-linuxkit-pr
#0 45.09 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#0 45.09 gyp ERR! cwd /app/node_modules/bufferutil
#0 45.09 gyp ERR! node -v v18.16.1
#0 45.09 gyp ERR! node-gyp -v v9.3.1
#0 45.09 gyp ERR! not ok
```

**Comment by ALLENWAN1** [comment]
@deepiksdev  ok. Sorry for the misunderstanding. I will test it tonight

**Comment by deepiksdev** [comment]
@ALLENWAN1 No problem at all, I finally managed to fix this issue this morning (see `buidocker` branch)
