### ISSUE TITLE
Test running the app locally without Docker

### ISSUE THREAD

**Issue by deepiksdev** [deepiksdev/dialoqbase#7]
This follows @ChristophePRAT's comment in https://github.com/n4ze3m/dialoqbase/issues/46#issuecomment-1613671278

**Comment by deepiksdev** [comment]
@ChristophePRAT  
When running `yarn install` in the `server` folder, I got the following error:
```
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/homebrew/Cellar/node/20.3.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:511:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Darwin 22.5.0
gyp ERR! command \"/opt/homebrew/Cellar/node/20.3.0/bin/node\" \"/opt/homebrew/Cellar/node/20.3.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--update-binary\" \"--module=/Users/emmanuel/Documents/GitHub/dialoqbase/server/node_modules/canvas/build/Release/canvas.node\" \"--module_name=canvas\" \"--module_path=/Users/emmanuel/Documents/GitHub/dialoqbase/server/node_modules/canvas/build/Release\" \"--napi_version=9\" \"--node_abi_napi=napi\" \"--napi_build_version=0\" \"--node_napi_label=node-v115\"
gyp ERR! cwd /Users/emmanuel/Documents/GitHub/dialoqbase/server/node_modules/canvas
gyp ERR! node -v v20.3.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp configure --fallback-to-build --update-binary --module=/Users/emmanuel/Documents/GitHub/dialoqbase/server/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/emmanuel/Documents/GitHub/dialoqbase/server/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/emmanuel/Documents/GitHub/dialoqbase/server/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:511:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
node-pre-gyp ERR! System Darwin 22.5.0
node-pre-gyp ERR! command \"/opt/homebrew/Cellar/node/20.3.0/bin/node\" \"/Users/emmanuel/Documents/GitHub/dialoqbase/server/node_modules/canvas/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\" \"--update-binary\"
node-pre-gyp ERR! cwd /Users/emmanuel/Documents/GitHub/dialoqbase/server/node_modules/canvas
node-pre-gyp ERR! node -v v20.3.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.10
node-pre-gyp ERR! not ok 
```
I fixed this error by running `yarn install --python="path_to_python3"`. I found "path_to_python3" by running `which python3`

**Comment by deepiksdev** [comment]
When running `yarn dev` in the main folder, I got the following error:
```
yarn run v1.22.19
$ pnpm --stream -r run dev
/bin/sh: pnpm: command not found
error Command failed with exit code 127.
```

I fixed it by running `npm install -g pnpm`

**Comment by deepiksdev** [comment]
When I run `yarn dev` from the main folder, I get what seems to be an endless loop. What I observe is similar to what is reported in https://github.com/vitejs/vite/discussions/13102

When I run `yarn dev` from the server folder, I get what seems to be a positive  feedback:
```
[App] [11:01:47.465] INFO (39017): Server listening at http://[::1]:3000
[App] [11:01:47.465] INFO (39017): Server listening at http://127.0.0.1:3000
``` 
However, when opening `http://127.0.0.1:3000` in Chrome, I get this:
``` 
{"message":"Route GET:/ not found","error":"Not Found","statusCode":404}
```
In the terminal, I get this:
```
[App] [11:06:01.699] INFO (39017): incoming request
[App]     reqId: "req-2"
[App]     req: {
[App]       "method": "GET",
[App]       "url": "/",
[App]       "hostname": "127.0.0.1:3000",
[App]       "remoteAddress": "127.0.0.1",
[App]       "remotePort": 56995
[App]     }
[App] [11:06:01.699] INFO (39017): Route GET:/ not found
[App]     reqId: "req-2"
[App] [11:06:01.701] INFO (39017): request completed
[App]     reqId: "req-2"
[App]     res: {
[App]       "statusCode": 404
[App]     }
[App]     responseTime: 1.7327920198440552
```

**Comment by deepiksdev** [comment]
@ChristophePRAT I have finally successfully installed the app by following your updated instructions, that I am copying here for future reference. Congrats !

## How to run locally
### Configure Redis
There are a few possible ways to deal with Redis. Please follow either one of these methods:
#### Running the Redis server locally
- Install [Redis](https://redis.io/download/). If you are on macOS, I strongly recommend using Homebrew by running: `brew install redis`
- Run `redis-server`
You should see information about the server, such as the port (for example `6379`). Your Redis URL (i.e. `DB_REDIS_URL`) will be: `redis://localhost:[PORT]`.

#### Running the Redis server using Upstash or Railway
Go to the official [Upstash](https://upstash.com/) or [Railway](https://railway.app/) website and follow the instructions to create a Redis server.
You should obtain a URL, which will be your `DB_REDIS_URL`.

### Run the app
1. Rename the example environment variables located at `app/ui/`, `app/widget/`, and `server/` to `.env`
2. Configure properly the environment variables. The ones located inside of the `app` folder can be used by default, but you must change the environment variables inside of the `server/` folder.
- `DATABASE_URL` is the URL of the PostgreSQL database
- `DB_REDIS_URL` should be set to the Redis URL. See the previous section for more details
- `OPENAI_API_KEY` is the OpenAI API key
- `DB_SECRET_KEY` is a random key that you can set to whatever you want
3. Run `yarn install` in the main folder and in the `server/` folder
4. Run `yarn build` in the main folder
5. Run `mv app/ui/dist server/dist/public && mv app/widget/dist/index.html server/dist/public/bot.html && cp -r app/widget/dist/assets/*  server/dist/public/assets/` in the main folder
6. Run `yarn dev` in the main folder **and** in the `server/` folder

From there you can open the app by using the URL printed by this last command.

<img width="1352" alt="Screenshot 2023-06-30 at 16 32 31" src="https://github.com/deepiksdev/dialoqbase/assets/2860170/c2e04bd6-132a-42b4-be93-260e615c5aad">
